karmada-io/dashboard

- .github/workflows/push-image.yml
- deploy/karmada-dashboard.yaml
Fixes issue: [dashboard#4](https://github.com/karmada-io/dashboard/issues/4)
> DASHBOARD: Add github workflow used to build the karmada-dashboard image

- deploy/karmada-dashboard-role.yaml
fix: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+
/kind feature
```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
```
Fixes #
```release-note
NONE
```
> use rbac.authorization.k8s.io/v1

- .github/workflows/push-image.yml
/kind bug
Fix ci build error, after upgrade `actions/download-artifact@v4`, it's not necessary to unzip artifact manually.
Fixes #44 
Upgrade other github actions:
- actions/setup-node to v4
- actions/upload-artifact to v4
```release-note
NONE
```
> build: upgrade github actions

- cmd/api/app/routes/namespace/handler.go
- ui/apps/dashboard/src/components/tag-list/index.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/namespace/index.tsx
- ui/apps/dashboard/src/services/base.ts
- ui/apps/dashboard/src/services/namespace.ts
Implement filter for `namespace` resource, optimize label display for medium or small device
1. Implement filter for `namespace` resource based on `dataselect`:
2. Optimize label display, for medium or small device, only show one label, users can hover `+1` to view the full labels.  for large device, no limit.
Fixes #
```release-note
1. Implement filter for `namespace` resource.
2. Optimize label display, for medium or small device.
```
> filter for namespace and optimize label display

- .github/workflows/push-image.yml
- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
/kind bug
/kind flake
Fixes #
- Fix ci build error：
CI build error 👉🏻：https://github.com/karmada-io/dashboard/actions/runs/10279472346/job/28444903136
in the PR: https://github.com/karmada-io/dashboard/pull/61/files
I updated the signature of `GetNamespaces`
https://github.com/karmada-io/dashboard/blob/48a9a9740c3a2c3436fb1319d68579e78a7af9c3/ui/apps/dashboard/src/services/namespace.ts#L17C1-L30C2
But did not update the invoke of `GetNamespaces` in  `src/pages/multicloud-resource-manage/workload/index.tsx`
https://github.com/karmada-io/dashboard/blob/48a9a9740c3a2c3436fb1319d68579e78a7af9c3/ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx#L34C3-L40C6
Then it …
> fix ci build error

- ui/apps/dashboard/src/components/panel/index.tsx
/kind bug
When we introduce the i18n feature for dashboard, it would cause the empty breadcrumbs. 
Comparison as following: 
before: 
after:
The reason is that `useMatches` only load once, and after that, even if the global route object refreshed, the `useMatches` hooks will not return the latest `matches` object.
https://github.com/karmada-io/dashboard/blob/650ef60ee15a29576702c45d518826d00bf23b59/ui/apps/dashboard/src/components/panel/index.tsx#L21
What I do is to traverse the global route object again, and get the sidebarName from the matched route entry.
Fixes #
```release-note
- fix the empty …
```
> fix: new method for generate breadcrumbs

- cmd/api/app/api.go
- cmd/api/app/routes/statefulset/handler.go
- pkg/resource/common/resourcechannels.go
- pkg/resource/statefulset/common.go
- pkg/resource/statefulset/detail.go
- pkg/resource/statefulset/list.go
- pkg/resource/statefulset/pods.go
- ui/apps/dashboard/src/components/tag-list/index.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/workload-detail-drawer.tsx
- ui/apps/dashboard/src/services/base.ts
- ui/apps/dashboard/src/services/workload.ts
/kind feature
this is an implementation of statefulset resources, including ui and api.
Fixes #
this feature branch is based on `feat/ns-filter`,  so the pr need be resolved after https://github.com/karmada-io/dashboard/pull/61
```release-note
- implement statefulset workload managing.
```
> implement statefulset resources

- pkg/resource/configmap/list_test.go
- ui/apps/dashboard/package.json
- ui/apps/dashboard/src/hooks/index.ts
- ui/apps/dashboard/src/hooks/use-namespace.ts
- ui/apps/dashboard/src/hooks/use-tag-num.ts
- ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/config-editor-modal.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/configmap-table.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/query-filter.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/config/index.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/config/store.ts
- ui/apps/dashboard/src/pages/multicloud-resource-manage/config/types.ts
- ui/apps/dashboard/src/services/base.ts
- ui/apps/dashboard/src/services/config.ts
- ui/pnpm-lock.yaml
/kind feature
1. add store management, we use zustand now
2. ui for configmap management
Fixes #
```release-note
- implement management for configmap under the config
- introduct zustand as store management
```
> UI for configmap management

- artifacts/dashboard/karmada-dashboard-configmap.yaml
- cmd/api/app/api.go
- cmd/api/app/routes/config/handler.go
- cmd/api/app/types/api/v1/config.go
- docs/user-guide.md
- pkg/config/config.go
- pkg/config/model.go
- ui/apps/dashboard/src/layout/sidebar.tsx
- ui/apps/dashboard/src/routes/route.tsx
- ui/apps/dashboard/src/services/dashboard-config.ts
/kind feature
Fixes #74 
```release-note
- add config for dashboard config, admin can control sidebar menu by editing the `karmada-dashboard-configmap` configmap.
```
> implementing feature of config for karmada dashboard

- cmd/web/app/options/options.go
- cmd/web/app/web.go
- go.mod
- pkg/config/config.go
- pkg/config/model.go
- ui/apps/dashboard/index.html
- ui/apps/dashboard/package.json
- ui/apps/dashboard/src/routes/index.tsx
- ui/apps/dashboard/src/services/base.ts
- ui/apps/dashboard/src/vite-env.d.ts
- ui/apps/dashboard/vite.config.ts
- ui/pnpm-lock.yaml
/kind feature
For enterprise's on-premises deployment, maybe the administrator can differentiate various functional systems or business lines through multiple paths under a single domain name. So there is need to implement the feature of PathPrefix to support on-premises deployment.
Fixes #96
```release-note
- add support for PathPrefix
```
> PathPrefix for karmada dashboard

- ui/apps/dashboard/vite.config.ts
/kind feature
As we modify the vite template for support feature of pathPrefix.
For the product development, the web app will replace the placeholder `{{PathPrefix}}`, the implement as following:
https://github.com/karmada-io/dashboard/blob/a8315b9b8a7a988e7756408c4ff08c93029f3908/cmd/web/app/web.go#L104-L117
But for local development,  the placeholder `{{PathPrefix}}` will not be replaced,  so we developd an vite plugin, for scenario of local development, the plugin will replace the placeholder `{{PathPrefix}}` before the html output to brower:
Fixes #
```release-note
- add replace-path-prefix vite …
```
> feat: implement replace-path-prefix vite plugin, for local dev

- artifacts/dashboard/karmada-dashboard-api.yaml
- artifacts/dashboard/karmada-dashboard-web.yaml
/kind cleanup
Updates and corrects the default image tag.
Fixes #
The steps to run the quick start demo would be:
1. launch Karmada: `hack/local-up-karmada.sh`
2. switch to host cluster and apply dashboards:
```
export KUBECONFIG=${HOME}/.kube/karmada.config
kubectl config use-context karmada-host
kubectl apply -f artifacts/dashboard/karmada-dashboard-sa.yaml
kubectl apply -f artifacts/dashboard/karmada-dashboard-api.yaml
kubectl apply -f artifacts/dashboard/karmada-dashboard-web.yaml
kubectl apply -f artifacts/dashboard/karmada-dashboard-configmap.yaml
```
3. expose the dashboard port to host:
```
kubectl port-forward -n karmada-system …
```
> Update default image tag

- README_cn.md
/kind bug
CN readme doesn't sync with EN readme for install karmada dashboard in nodeport mode.
BTW, optimize the dashboard url in cn reamde
Fixes #
```release-note
NONE
```
> fix: script typo error in cn readme

- cmd/api/app/api.go
- cmd/api/app/routes/cronjob/handler.go
- pkg/resource/common/resourcechannels.go
- pkg/resource/cronjob/common.go
- pkg/resource/cronjob/detail.go
- pkg/resource/cronjob/events.go
- pkg/resource/cronjob/jobs.go
- pkg/resource/cronjob/list.go
/kind design
Add api for cronjob resource management.
Fixes #
```release-note
NONE
```
> feat: add api for cronjob resources

- .github/workflows/ci.yml
- Makefile
/kind feature
- precheck build error when contributor submit PR 
some mock-case:
1. if contributor submit invalid goland code, like
the ci-workflow will report error like following:
2. if contributor submit invalid frontend code, like
the ci-workflow will report error like following:
Fixes #102
```release-note
NONE
```
> ci: setup ci-workflow for PR

- .github/workflows/ci.yml
- charts/karmada-dashboard/templates/karmada-dashboard-configmap.yaml
- charts/karmada-dashboard/templates/karmada-dashboard-web.yaml
/kind bug
fix #120
```release-note
none
```
/cc @warjiang @RainbowMango
> charts: add the missing dashboard configmap

- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/new-workload-editor-modal.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/workload-detail-drawer.tsx
/kind feature
- implement web ui for job and cronjob resources
- 
Fixes #
```release-note
- add `job/cronjob` tab switcher under the workload resource.
```
> feat: add ui for job and cronjob

- cmd/api/app/api.go
- cmd/api/app/routes/clusterpropagationpolicy/handler.go
- pkg/common/types/resourcekind.go
- pkg/resource/clusterpropagationpolicy/common.go
- pkg/resource/clusterpropagationpolicy/detail.go
- pkg/resource/clusterpropagationpolicy/list.go
/kind feature
implement feature for curd of cluster propagation policy resource
Fixes #
```release-note
NONE
```
> feat: add api for clusterpropagationpolicy resource

- cmd/api/app/api.go
- cmd/api/app/routes/clusteroverridepolicy/handler.go
- cmd/api/app/routes/overridepolicy/handler.go
- cmd/api/app/types/api/v1/overridepolicy.go
- pkg/common/types/resourcekind.go
- pkg/resource/clusteroverridepolicy/common.go
- pkg/resource/clusteroverridepolicy/detail.go
- pkg/resource/clusteroverridepolicy/list.go
- pkg/resource/overridepolicy/common.go
- pkg/resource/overridepolicy/detail.go
- pkg/resource/overridepolicy/list.go
/kind feature
as the op management (for ospp 2024) didn't finished, so we decided to finish the rest of work by ourselves. The pr contains rest api for overridepolicy and clusteroverridepolicy management.
https://github.com/karmada-io/dashboard/pull/132
```release-note
NONE
```
> feat: rest api for op and cluster op

- ui/apps/dashboard/src/pages/multicloud-policy-manage/override-policy/index.tsx
- ui/apps/dashboard/src/pages/multicloud-policy-manage/override-policy/override-policy-editor-drawer.tsx
- ui/apps/dashboard/src/services/overridepolicy.ts
/kind feature
as the op management (for ospp 2024) didn't finished, so we decided to finish the rest of work by ourselves. The pr contains ui for overridepolicy and clusteroverridepolicy management.
https://github.com/karmada-io/dashboard/pull/132
```release-note
- add management for overridepolicy and cluster overridepolicy
```
> feat: ui for op and cluster op

- .github/workflows/codeql-analysis.yml
- .github/workflows/push-image.yml
/kind cleanup
Pin Github runner to the official release, not the latest. 
Fixes #
The latest release might break our tests unexpectedly because the software installation might be different between releases.
```release-note
NONE
```
> pin github action runner to ubuntu-22.04 not the latest

- .gitignore
- Makefile
/kind feature
```bash
❯ make help
Karmada Dashboard Makefile
Usage:
make              - Build all binaries (same as 'make all')
make all          - Build all binaries
make install      - Install all dependencies
make run          - Run both API and Web servers
make images       - Build all Docker images
Development Commands:
make run-api      - Run API server only
make run-web      - Run Web server only
make install-deps - Install Go dependencies
make install-ui-deps - Install UI dependencies
Build Commands:
make build        - Build all binaries
make images       - Build all Docker images
Variables:
KUBECONFIG       - Path to karmada kubeconfig file
API_PORT         - API server port (default: 8000)
API_HOST         - API server host (default: …
```
> update Makefile, make development simpler

- ui/apps/dashboard/src/main.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/workload-detail-drawer.tsx
- ui/apps/dashboard/src/utils/time.ts
/kind bug
The duration of workload is hard coded in the frontend code, just fix that.
Fixes #169 
```release-note
- fix the duration calculation for workload 
```
> fix duration for workload

- cmd/metrics-scraper/app/scrape/other.go
- hack/verify-staticcheck.sh
- pkg/client/init.go
- pkg/dataselect/dataselect_test.go
- pkg/resource/common/resourcechannels.go
- pkg/resource/cronjob/detail.go
- pkg/resource/cronjob/events.go
- pkg/resource/cronjob/jobs.go
- pkg/resource/cronjob/list.go
- pkg/resource/daemonset/common.go
- pkg/resource/daemonset/detail.go
- pkg/resource/daemonset/list.go
- pkg/resource/deployment/detail.go
- pkg/resource/deployment/list.go
- pkg/resource/job/events.go
- pkg/resource/job/list.go
- pkg/resource/statefulset/list.go
/kind cleanup
format code about whitespace
Fixes part of karmada-io/karmada#6078
```release-note
NONE
```
> chore: format code about whitespace

- cmd/api/app/routes/cluster/handler.go
- cmd/api/app/routes/clusteroverridepolicy/handler.go
- cmd/api/app/routes/clusterpropagationpolicy/handler.go
- cmd/api/app/routes/overridepolicy/handler.go
- cmd/api/app/routes/overview/misc.go
- cmd/api/app/routes/propagationpolicy/handler.go
- hack/verify-staticcheck.sh
- pkg/client/init.go
- pkg/config/config.go
- pkg/resource/cronjob/jobs.go
/kind cleanup
chore: format code about misspell,staticcheck,govet
Fixes part of  https://github.com/karmada-io/karmada/issues/6078
```release-note
```
> chore: format code about misspell,staticcheck,govet

- cmd/api/app/routes/unstructured/handler.go
- ui/apps/dashboard/src/pages/multicloud-resource-manage/namespace/index.tsx
- ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx
- ui/apps/dashboard/src/services/workload.ts
/kind bug
we use unified raw api to delete namespace resources, but it should not set default namespace when resource kind is namespace resource. Also fix the alert message, if delete namespace successfully, it should use `messageApi.success` method
Fixes #
```release-note
NONE
```
> fix delete namespace in control plane

- cmd/api/app/api.go
- cmd/api/app/routes/cluster/accesscluster.go
- cmd/api/app/routes/cluster/handler.go
- cmd/api/app/routes/clusteroverridepolicy/handler.go
- cmd/api/app/routes/clusterpropagationpolicy/handler.go
- cmd/metrics-scraper/app/metricsscraper.go
- cmd/metrics-scraper/app/routes/metrics/handlerqueries.go
- cmd/metrics-scraper/app/scrape/other.go
- cmd/metrics-scraper/app/scrape/scrape.go
- cmd/web/app/web.go
- hack/verify-staticcheck.sh
- pkg/common/errors/handler.go
- pkg/environment/version.go
/kind cleanup
chore: format code about errcheck,gosimple,ineffassign,unused
Fixes part of https://github.com/karmada-io/karmada/issues/6078
```release-note
```
> chore: format code about errcheck,gosimple,ineffassign,unused

- .github/workflows/push-image.yml
- Makefile
- cluster/images/Dockerfile
- cluster/images/build-web.Dockerfile
- cluster/images/buildx.Dockerfile
/kind feature
add multi platforms build because some users need arm64 image => https://github.com/karmada-io/dashboard/issues/164
and we have plan to add support for arm64: https://github.com/karmada-io/dashboard/issues/121
Fixes #164
Fixes #121
```release-note
NONE
```
> ci: add multi-platform image build for karmada-dashboard

- .github/workflows/ci.yml
- .github/workflows/dockerhub-latest-image.yml
- .github/workflows/dockerhub-released-image.yml
- .github/workflows/push-image.yml
/kind bug
upgrade pnpm version otherwise pnpm will install latest dependencies instead of following the pnpm-lock file
Fixes #
```release-note
NONE
```
> ci: upgrade pnpm to 9.1.2

- cmd/api/app/api.go
- cmd/api/app/routes/auth/me.go
- cmd/api/app/routes/terminal/handler.go
- cmd/api/app/routes/terminal/model.go
- cmd/api/app/routes/terminal/terminal.go
- cmd/api/app/types/common/response.go
- go.mod
- go.sum
- pkg/common/types/kubernetes.go
- pkg/common/types/resourcekind.go
- pkg/resource/common/condition.go
- pkg/resource/common/pod.go
- pkg/resource/common/resourcestatus.go
This is part of PR => https://github.com/karmada-io/dashboard/pull/213
this pr implement the api for web terminal feature in the karmada control plane, the code may be reused in member cluster management. 
Here I'll co-author with @MdSayemkhan
/kind feature
Fixes #57 
```release-note
NONE
```
> add api for karmada web terminal

- .github/workflows/ci.yml
- .gitignore
- ui/apps/dashboard/e2e/login.spec.ts
- ui/apps/dashboard/package.json
- ui/apps/dashboard/playwright.config.ts
- ui/apps/dashboard/src/pages/login/index.tsx
- ui/apps/dashboard/tsconfig.json
- ui/pnpm-lock.yaml
Add Playwright E2E testing framework to Karmada Dashboard
Basic Playwright configuration for E2E testing
Login page test as foundation for future test coverage
NPM scripts for running E2E tests
Establishes automated testing foundation for UI stability
Enables regression testing during development
Provides framework for testing critical user workflows
Login page loads and renders correctly
Full authentication flow (ready for expansion)
```
pnpm test:e2e        # headless mode
pnpm test:e2e:headed # with browser UI
```
> Add Playwright E2E testing framework to Karmada Dashboard
