karmada-io/dashboard

.github/workflows/push-image.yml
Signed-off-by: RainbowMango <qdurenhongcai@gmail.com>
=> Update image publish workflow

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/flaking-test.md, .github/ISSUE_TEMPLATE/good-first.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: RainbowMango <qdurenhongcai@gmail.com>
=> Setup PR and issue template

README.md, deploy/karmada-dashboard.yaml
/kind documentation
update url of yaml in README
Fixes #
```release-note
NONE
```
=> update url of yaml in README

OWNERS
/kind cleanup
Setup owner files.
Fixes #
```release-note
NONE
```
=> Setup owner files

.github/workflows/codeql-analysis.yml
/kind feature
CodeQL is the analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis.
In CodeQL, code is treated as data. Security vulnerabilities, bugs, and other errors are modeled as queries that can be executed against databases extracted from code. You can run the standard CodeQL queries, written by GitHub researchers and community contributors, or write your own to use in custom analyses. Queries that find potential bugs highlight the result directly in the source file.
Fixes #
```release-note
NONE
```
=> feat: Add Github CodeQL security checks for Javascript

OWNERS
/kind cleanup
@warjiang and @samzong now leading the effort of the dashboard project.
Fixes #
```release-note
NONE
```
=> add wenjiang and samzong onto the owner list

docs/user-guide.md
/kind documentation
Fixes #59 
@warjiang 
I change the shell to 
```
cp hack/images/image.list.load.online.example  hack/images/image.list.load.online
bash hack/ops/load-images.sh hack/images/image.list.load.online
```
=> Renewing docs/user-guide.md

hack/local-up-karmada.sh
/kind bug
fix start local test-env with `local-up-karmada.sh` script
Fixes #
```release-note
NONE
```
=> fix: script error for start test-env

ui/apps/dashboard/src/layout/index.tsx, ui/apps/dashboard/src/layout/sidebar.tsx
/kind feature
Fixes #78 
Enhanced responsive layout and sidebar navigation with optimized route handling and performance improvements.
<!--
If no, just write "NONE" in the release-note block below.
If yes, a release note is required.
=> Improve Responsive Layout and Sidebar Navigation

ui/apps/dashboard/src/layout/sidebar.tsx
/kind cleanup
Fixes #90 
@warjiang Thank you for pointing out the error.
=> Fix antd menu warning by removing inlineCollapsed

README.md, deploy/karmada-dashboard-secret.yaml
/kind feature
Creating a ServiceAccount does not automatically generate Secret in v1.24+
NONE
NONE
NONE
```release-note
```
=> add create secret for k8s v1.24+

cmd/api/app/api.go, cmd/api/app/routes/secret/handler.go, pkg/resource/secret/common.go, pkg/resource/secret/detail.go, pkg/resource/secret/list.go, ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/query-filter.tsx, ui/apps/dashboard/src/pages/multicloud-resource-manage/config/components/secret-table.tsx, ui/apps/dashboard/src/pages/multicloud-resource-manage/config/index.tsx, ui/apps/dashboard/src/services/config.ts
/kind feature
- add rest api for secret manage
- and corresponding ui for secret manage
Fixes #
```release-note
- add secret manage
```
=> secret manage

cmd/api/app/api.go, cmd/api/app/routes/daemonset/handler.go, pkg/resource/common/resourcechannels.go, pkg/resource/daemonset/common.go, pkg/resource/daemonset/detail.go, pkg/resource/daemonset/list.go, ui/apps/dashboard/src/pages/multicloud-resource-manage/workload/index.tsx, ui/apps/dashboard/src/services/base.ts, ui/apps/dashboard/src/services/workload.ts
/kind feature
- add rest api for daemonset manage
- and corresponding ui for daemonset manage
Fixes #
```release-note
- implement management of daemonset
```
=> daemonset manage

artifacts/kindClusterConfig/member2.yaml
For local develepment
Fixes #
```release-note
```
=> fix: kind cluster config member2

README.md, README_cn.md
/kind cleanup
Add meeting info to the README file.
Fixes #
```release-note
NONE
```
=> Update Readme with meeting info

cmd/api/app/api.go, cmd/api/app/routes/job/handler.go, pkg/resource/common/resourcechannels.go, pkg/resource/job/common.go, pkg/resource/job/detail.go, pkg/resource/job/events.go, pkg/resource/job/list.go, pkg/resource/job/pods.go
/kind feature
Add api for job resources.
Fixes #
```release-note
NONE
```
=> feat: add api for job resource

cmd/api/app/api.go, cmd/api/app/routes/service/handler.go, pkg/resource/common/endpoint.go, pkg/resource/common/resourcechannels.go, pkg/resource/common/serviceport.go, pkg/resource/endpoint/endpoint.go, pkg/resource/endpoint/list.go, pkg/resource/service/common.go, pkg/resource/service/detail.go, pkg/resource/service/events.go, pkg/resource/service/list.go
/kind feature
- implement management for service
- export rest api for frontend web-ui
- 
Fixes #
```release-note
NONE
```
=> feature: add service management

charts/karmada-dashboard/templates/_helpers.tpl, charts/karmada-dashboard/templates/karmada-dashboard-api.yaml, charts/karmada-dashboard/templates/karmada-dashboard-sa.yaml, charts/karmada-dashboard/templates/karmada-dashboard-web-service.yaml, charts/karmada-dashboard/values.yaml
/kind bug
After this patch, installing the chart using the default values ​​will succeed.
Fixes #
```release-note
```
/cc @warjiang
=> charts: fix several bugs, make the default config work

charts/karmada-dashboard/templates/karmada-dashboard-web-service.yaml, charts/karmada-dashboard/values.yaml
/kind feature
Fixes #
```release-note
Support configuring nodePort for the dashboard web.
```
/cc @warjiang
=> charts: support configuring nodePort for the dashboard web

ui/packages/i18n-tool/src/scan/translate.js
/kind flake
keep the format of locale files to avoid too many changes in locale files. 
Fixes #
```release-note
NONE
```
=> feat: update locale file format & add extra log

cmd/api/app/api.go, cmd/api/app/routes/clusterpropagationpolicy/handler.go, pkg/common/types/resourcekind.go, pkg/resource/clusterpropagationpolicy/common.go, pkg/resource/clusterpropagationpolicy/detail.go, pkg/resource/clusterpropagationpolicy/list.go
/kind feature
- implement api for cluster propagation policy
Fixes #
```release-note
NONE
```
=> Add api for clusterpp

ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/index.tsx, ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/propagation-policy-editor-drawer.tsx, ui/apps/dashboard/src/services/propagationpolicy.ts
/kind feature
optimize the ui for pp, including
-  unified view of yaml content
-  allow user filter pp by name or by namespace 
Fixes #
```release-note
- optimize the ui for pp(including view of pp、opt for filtering by pp's name or namespace)
```
=> feat: optimize the ui for pp

ui/apps/dashboard/src/App.tsx, ui/apps/dashboard/src/components/navigation/index.tsx, ui/apps/dashboard/src/components/tag-list/helper.ts, ui/apps/dashboard/src/components/tag-list/index.tsx
opt for dashboard ui components
/kind cleanup
- clean duplicate messageApi usage
- clean warning in the console
- add helper method of taglist
Fixes #
```release-note
NONE
```
=> clean duplicate code & warning in dashboard ui

.github/workflows/ci.yml
/kind bug
make pnpm version in ci.yml consist with packageManager in package.json.
Fixes #183
fix the build error for frontend, more details can visit: https://github.com/karmada-io/dashboard/pull/183#issuecomment-2635639335
```release-note
NONE
```
=> fix: update the version of pnpm in ci

cmd/api/app/routes/overview/misc.go, cmd/metrics-scraper/app/routes/metrics/handlerqueries.go, cmd/metrics-scraper/app/scrape/other.go, hack/verify-staticcheck.sh, pkg/common/errors/localizer.go
/kind cleanup
chore: format code about gocyclo,gosec
Fixes part of https://github.com/karmada-io/karmada/issues/6078
```release-note
```
=> chore: format code about gocyclo,gosec

pkg/resource/propagationpolicy/list.go, ui/apps/dashboard/src/pages/multicloud-policy-manage/propagation-policy/index.tsx, ui/apps/dashboard/src/services/propagationpolicy.ts
/kind bug
the related-resource column in the propagation policy page is wrong, just fix it.
Fixes #
```release-note
NONE
```
=> fix: update related resources for propagationpolicy

.github/workflows/dockerhub-latest-chart.yml, .github/workflows/dockerhub-released-chart.yml, Makefile, hack/package-helm-chart.sh, hack/util.sh
/kind feature
Add ci for latest/released chart
Fixes #
```release-note
NONE
```
=> add ci for latest/released chart

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml
/kind feature
Fixes #
```release-note
NONE
```
=> add ci for latest/released image

cmd/api/app/routes/cluster/handler.go, pkg/client/client.go
/kind cleanup
when reviewing the code, find some typo errors and then fix it.
Fixes #
```release-note
NONE
```
=> fix: typo error in pkg/client

cluster/images/Dockerfile, cluster/images/build-web.Dockerfile, cluster/images/buildx.Dockerfile
/kind cleanup
ustc mirror for alpine not suitable for global project, so we need to clean that and use the original mirror for alpine
Fixes #
```release-note
NONE
```
=> clean: rm ustc alpine mirror

cluster/images/build-terminal.Dockerfile
Fixes #57
```release-note
None
```
=> add Dockerfile for Karmada Dashboard web terminal

cmd/api/app/routes/terminal/handler.go, cmd/api/app/routes/terminal/terminal.go, pkg/resource/common/event.go, pkg/resource/common/resourcechannels.go, ui/apps/dashboard/package.json, ui/apps/dashboard/src/components/icons/index.tsx, ui/apps/dashboard/src/components/navigation/index.module.less, ui/apps/dashboard/src/components/navigation/index.tsx, ui/apps/dashboard/src/components/terminal/index.tsx, ui/apps/dashboard/src/components/terminal/karmada-terminal.tsx, ui/apps/dashboard/src/layout/header.tsx, ui/apps/dashboard/src/layout/index.tsx, ui/apps/dashboard/src/services/terminal.ts, ui/apps/dashboard/src/store/global.ts, ui/apps/dashboard/vite.config.ts, ui/pnpm-lock.yaml
This is part of PR => https://github.com/karmada-io/dashboard/pull/213
this pr implement the api for web terminal feature in the karmada control plane, the code may be reused in member cluster management.
Here I'll co-author with @MdSayemkhan
this PR is focused on the web-ui implementation of web-terminal on karmada control-plane
Fixes #57 
Notice, this PR is based on PR #223, it should be merged after PR#223 be merged
```release-note
- add web-terminal entrance in the navigation bar
```
=> feat(ui): karmada web terminal UI

cmd/web/app/options/options.go, cmd/web/app/web.go
/kind feature
as we lift code from kubernetes dashboard upstream, and add extra deployment for that, we should proxy unified api endpoints for web-ui, so add extra proxy for kubernetes-dashboard-api module.
Fixes #
```release-note
NONE
```
=> feat(karmada-dashboard-web): add proxy to kubernetes-dashboard-api

Makefile, cmd/api/app/options/options.go, pkg/config/config.go
/kind feature
This PR introduces the foundational configuration for Karmada-MCP-Server feature. It adds the necessary command-line flags and options in `options.go`  to support both MCP  and OpenAI integrations.
Fixes #273 
```release-note
NONE
```
=> feat(config): add base configuration for MCP integration
